---
- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "ghcr.io/linuxserver/sonarr"
    pull: yes
    networks:
      - name: swag_internal_macvlan
        ipv4_address: "{{ ip_address }}"
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "{{ docker_dir }}/{{ container_name }}:/config"
      - "{{ mergerfs_root }}/Media/TV:/tv"
      - "{{ mergerfs_root }}/Downloads:/downloads"
    restart_policy: unless-stopped
    ports:
      - 8989:8989
