---
- name: Install the iptables.sh config
  copy:
    src: "files/iptable.sh"
    dest: "{{ docker_dir }}/{{ container_name }}/iptable.sh"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Make sure the Deluge container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "binhex/arch-delugevpn:latest"
    pull: yes
    networks:
      - name: swag_internal_macvlan
        ipv4_address: 10.0.0.10
    privileged: yes
    sysctls:
      "net.ipv4.conf.all.src_valid_mark": "1"
    capabilities: 
      - net_admin
    state: 'started'
    env:
      "VPN_ENABLED": "yes"
      "VPN_PROV": custom
      "VPN_CLIENT": "wireguard"
      "ENABLE_PRIVOXY": "yes"
      "NAME_SERVERS": "{{ ','.join(dns_nameservers) }}"
      "LAN_NETWORK": "172.20.0.0/16, {{ lan_network }}"
      "DELUGE_DAEMON_LOG_LEVEL": "info"
      "DELUGE_WEB_LOG_LEVEL": "info"
      "DEBUG": "true"
      "UMASK": "000"
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/data:/data"
      - "{{ docker_dir }}/{{ container_name }}/config:/config"
      - "{{ docker_dir }}/{{ container_name }}/iptable.sh:/root/iptable.sh"
      - "{{ mergerfs_root }}/Downloads:/home/nobody/Downloads"
      - "{{ mergerfs_root }}/Backups/Linux:/.linux"
      - "/etc/localtime:/etc/localtime:ro"
    restart_policy: unless-stopped
