---
- name: Make sure the Prometheus container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "prom/prometheus"
    pull: yes
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - name: swag_internal_macvlan
        ipv4_address: "{{ ip_address }}"
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    user: "1001"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/etc:/etc/prometheus"
      - "{{ docker_dir }}/{{ container_name }}/prometheus:/prometheus"
    restart_policy: unless-stopped
