#
# Misc
#
timezone: Europe/Amsterdam

ntp_timezone: "{{ timezone }}"

username: notthebee

ssh_public_key: https://github.com/notthebee.keys

guid: "1000"

shell: /usr/bin/fish

docker_dir: /opt/docker/data

dotfiles_repo: https://github.com/notthebee/dotfiles


#
# Email credentials (for SMART and Snapraid error reporting)
#

email: moe@notthebe.ee

email_login: "{{ email }}"

email_smtp_host: smtp.mailbox.org

email_smtp_port: 465

# MSMTP 
msmtp_accounts:
- account:   mailbox
  host:      "{{ email_smtp_host }}"
  port:      "{{ email_smtp_port }}"
  auth:      "on"
  from:      "{{ email }}"
  user:      "{{ email }}"
  password:  "{{ email_password}}"

msmtp_default_account: "mailbox"

msmtp_alias_default : "{{ email }}"


#
# SSH (geerlingguy.security)
#
security_ssh_port: 69

security_sudoers_passwordless: [ "{{ username }}" ]

security_autoupdate_reboot: "true"

host: "{{ duckdns_domain }}.duckdns.org"


#
# Docker
#
copy_persistent_data: false

force_copy_persistent_data: false

enable_smarthome: true

enable_plex: true

enable_downloaders: true

enable_deluge: true

enable_bitwarden: true

enable_duckdns: true

enable_homer: true

enable_nextcloud: true

enable_swag: true

enable_wireguard: true


#
# Samba
#
samba_server_string: "{{ hostname }}"

samba_users:
  - name: "{{ username }}"
    password: "{{ password }}"
  - name: "{{ additional_users[0].name }}"
    password: "{{ password2 }}"

samba_global_include: global-include.conf

samba_mitigate_cve_2017_7494: false

samba_shares:
  - name: Trash
    guest_ok: no
    public: no
    read_only: no
    writable: yes
    browseable: yes
    path: "{{ mergerfs_root }}"
    valid_users: "{{ username }}"
    write_list: "{{ username }}"
      
  - name: Downloads
    guest_ok: no
    public: no
    read_only: no
    writable: yes
    browseable: yes
    path: "{{ mergerfs_root }}/Downloads"
    valid_users: "{{ username }}, {{ additional_users[0].name }}"
    write_list: "{{ username }}, {{ additional_users[0].name }}"
 
  - name: Media
    guest_ok: no
    public: no
    read_only: no
    writable: yes
    browseable: yes
    path: "{{ mergerfs_root }}/Media"
    valid_users: "{{ username }}, {{ additional_users[0].name }}"
    write_list: "{{ username }}, {{ additional_users[0].name }}"



#
# Time Machine
#
timemachine_root: /mnt/timemachine

timemachine_drive: /dev/disk/by-label/TimeMachine

enable_timemachine: true


#
# Snapraid and MergerFS
#
mergerfs_root: /mnt/storage

disks:
  - { name: /mnt/data1, src: /dev/disk/by-label/Data1, content: true }
  - { name: /mnt/data2, src: /dev/disk/by-label/Data2, content: true }

parity_disks:
  - { name: /mnt/parity1, src: /dev/disk/by-label/Parity1, content: true }

snapraid_runner_gmail_pass: "{{ email_password }}"

snapraid_runner_email_address: "{{ email }}"

snapraid_runner_email_address_from: "{{ snapraid_runner_email_address }}"

snapraid_runner_email_address_to: "{{ snapraid_runner_email_address }}"

snapraid_runner_smtp_host: "{{ email_smtp_host }}"

snapraid_runner_smtp_port: "{{ email_smtp_port }}"

snapraid_runner_email_sendon: "error"

snapraid_runner_use_ssl: true

snapraid_content_files:
  - disks[0].name/snapraid.content
  - /var/snapraid.content

snapraid_config_excludes:
  - "*.unrecoverable"
  - /lost+found/
  - "*.!sync"
  - /tmp/
  - "Downloads"

