---
- name: Set the architecture variable
  set_fact:
    arch: "armhf"
  when: '"armv" in ansible_architecture'

- name: Set the architecture variable
  set_fact:
    arch: "amd64"
  when: '"x86_64" in ansible_architecture'

- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: 'ikev2'
    image: "notthebee/ikev2:{{ arch }}"
    privileged: yes
    pull: yes
    state: 'started'
    env:
      DNS_SERVERS: "{{ ansible_default_ipv4.address }}"
      VPNHOST: "{{ host }}"
      EMAILADDR:  "{{ email }}"
      VPNUSERNAME:  "{{ username }}"
      VPNPASSWORD:  "{{ vpn_password }}"
      EXCLUDE_SSIDS: "{{ ikev2_excludedssids }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/config:/config"
      - "{{ docker_dir }}/{{ container_name }}/letsencrypt:/etc/letsencrypt"
    ports:
      - 80:80/tcp
      - 4500:4500/udp
      - 500:500/udp
    restart_policy: unless-stopped


- name: Copy the mobileconfig to the local host (might fail on the first run)
  ignore_errors: true
  synchronize:
    mode: pull
    delete: yes
    src: "{{ docker_dir }}/{{ container_name }}/config/{{ host }}.mobileconfig"
    dest: "~/.ansible/ikev2/{{ host }}.mobileconfig"