---
- name: Set the name of a sudo group
  set_fact:
    sudo_group: sudo
   
- name: Create a login user
  become: yes
  user:
    name: "{{ username }}"
    password: "{{ password | password_hash('sha512') }}"
    groups: 
      - "{{ sudo_group }}"
      - users
    state: present
    append: true
    update_password: on_create
 
- name: Ensure group "{{ username }}" exists
  become: yes
  group:
    name: "{{ username }}"
    state: present
 
- name: Append the samba group
  when: enable_samba | default(False) 
  become: yes
  user:
    name: "{{ username }}"
    groups: 
      - sambashare
    append: true

- name: Allow 'sudo' group to have passwordless sudo
  become: yes
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%{{ sudo_group }}'
    line: '%{{ sudo_group }} ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: Copy the public SSH key 
  become: yes
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ ssh_public_key }}"

- name: Create additional users (no login)
  become: yes
  user:
    name: "{{ item.name }}"
    groups: "{{ item.groups }}"
    password: "{{ item.password | password_hash('sha512') }}"
    update_password: on_create
    state: present
    append: true
    shell: /sbin/nologin
  with_items: "{{ additional_users }}"
  when: additional_users is defined
  no_log: true
