- name: Mount the data drives
  mount:
    name: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: xfs
    state: mounted
    passno: "2"
  with_items: "{{ disks }}"
  when: disks[0] is defined

- name: Mount the cache drives
  mount:
    name: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: ext4
    state: mounted
    opts: defaults,discard
    passno: "2"
  with_items: "{{ cache_disks }}"
  when: cache_disks[0] is defined

- name: Mount the parity drives
  mount:
    name: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: xfs
    state: mounted
    passno: "2"
  with_items: "{{ parity_disks }}"
  when: parity_disks[0] is defined

- name: Mount the mergerfs cached array
  mount:
    name: "{{ mergerfs_root }}"
    src: /mnt/storage_cache:/mnt/storage_slow
    opts: category.create=lfs,direct_io,defaults,allow_other,moveonenospc=1,minfreespace=50G,fsname=mergerfs,uid=1000,gid=1000
    fstype: fuse.mergerfs
    state: mounted
  when: disks[0] is defined

- name: Mount the mergerfs array
  mount:
    name: "{{ mergerfs_root }}_slow"
    src: /mnt/data*
    opts: direct_io,defaults,allow_other,moveonenospc=1,minfreespace=500G,fsname=mergerfs_slow,uid=1000,gid=1000
    fstype: fuse.mergerfs
    state: mounted
  when: disks[0] is defined

- name: Mount the mergerfs cache only array
  mount:
    name: "{{ cache_root }}"
    src: /mnt/cache*
    opts: direct_io,defaults,allow_other,fsname=mergerfs_cache,category.create=mfs
    fstype: fuse.mergerfs
    state: mounted
  when: cache_disks[0] is defined

- name: Mount the Time Machine drive
  mount:
    name: "{{ timemachine_root }}"
    src: "{{ timemachine_drive }}"
    fstype: ext4
    opts: defaults,discard
    state: mounted
    passno: "2"
  when: enable_timemachine | default(False)
