---
- name: Set the name of a sudo group
  set_fact:
    sudo_group: sudo

- name: Ensure the necessary groupsexists
  group:
    name: "{{ item }}"
    state: present
  loop:
      - "{{ username }}"
      - docker
   
- name: Create a login user
  user:
    name: "{{ username }}"
    password: "{{ password | password_hash('sha512') }}"
    groups: 
      - "{{ sudo_group }}"
      - docker
      - users
    state: present
    append: true

- name: Chmod the user home directory
  file:
    path: "/home/{{ username }}"
    state: directory
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"
    recurse: yes

- name: Allow '{{ sudo_group }}' group to have passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%{{ sudo_group }}'
    line: '%{{ sudo_group }} ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: Copy the public SSH key 
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ ssh_public_key }}"

- name: Set the default shell
  user: 
    name: "{{ username }}"
    shell: "{{ shell }}"

- name: Disable fish greeting
  lineinfile:
    path: /home/{{ username }}/.config/fish/fish_variables
    state: present
    regexp: 'fish_greeting:.+'
    line: 'SETUVAR fish_greeting:'
    create: true
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
  when: '"fish" in shell'

- name: Suppress login messages
  file:
    name: /home/{{ username }}/.hushlogin
    mode: 0644
    state: touch
    owner: "{{ username }}"
    group: "{{ username }}"
    modification_time: preserve
    access_time: preserve

- name: Disable cron e-mail notifications
  cron:
    name: MAILTO
    user: "{{ username }}"
    env: yes
    job: ""
