---

snapraid_install: true
snapraid_runner: true

snapraid_apt_package_name: snapraid
snapraid_bin_path: /usr/local/bin/snapraid
snapraid_force_install: false

snapraid_runner_healthcheck_io_uuid: ""
snapraid_healthcheck_io_host: https://hc-ping.com

snapraid_runner_email_address: ""
snapraid_runner_gmail_pass: ""
snapraid_runner_email_address_from: "{{ snapraid_runner_email_address }}"
snapraid_runner_email_address_to: "{{ snapraid_runner_email_address }}"
snapraid_runner_email_sendon: "error"

snapraid_runner_smtp_host: smtp.gmail.com
snapraid_runner_smtp_port: 465
snapraid_runner_use_ssl: true

snapraid_content_files:
  - /var/snapraid.content

snapraid_config_excludes: []
snapraid_config_hidden_files_enabled: false
snapraid_config_hidden_files: nohidden
snapraid_config_path: /etc/snapraid.conf

snapraid_runner_path: /opt/snapraid-runner/snapraid-runner
snapraid_runner_conf: "{{ snapraid_runner_path }}.conf"
snapraid_runner_bin: "{{ snapraid_runner_path }}.py"
snapraid_runner_command: "python3 {{ snapraid_runner_bin }} -c {{ snapraid_runner_conf }} {% if snapraid_runner_healthcheck_io_uuid %}| curl -fsS -m 10 --retry 5 -o /dev/null --data-binary '@-' {{ snapraid_healthcheck_io_host }}/{{ snapraid_runner_healthcheck_io_uuid }} > /dev/null{% endif %}"
snapraid_runner_scrub: true
snapraid_runner_scrub_percent: 22
snapraid_runner_scrub_age: 8
snapraid_runner_touch: true
snapraid_runner_delete_threshold: 250

snapraid_runner_cron_jobs:
  - { job: '{{ snapraid_runner_command }}', name: 'snapraid_runner', weekday: '*', hour: '01' }

snapraid_sync_schedule:
  minute: 0
  hour: 0
snapraid_sync_healthcheck_io_uuid: ""

snapraid_scrub_schedule:
  minute: 0
  hour: 0
  weekday: 0
snapraid_scrub_healthcheck_io_uuid: ""
