---
- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "ghcr.io/linuxserver/radarr"
    pull: yes
    networks:
      - name: swag_internal_macvlan
        ipv4_address: 10.0.0.15
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ docker_dir }}/{{ container_name }}:/config"
      - "{{ mergerfs_root }}/Media/Movies:/movies"
      - "{{ mergerfs_root }}/Downloads:/downloads"
    restart_policy: unless-stopped
