---
- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "evanbuss/openbooks"
    pull: yes
    state: 'started'
    labels:
      "flame.type": "application"
      "flame.name": "{{ dashboard_name }}"
      "flame.url": "{{ dashboard_url }}"
      "flame.icon": "custom"
    env:
      "TZ": "{{ timezone }}"
    restart_policy: unless-stopped

- name: Add {{ container_name }} to the internal network
  docker_network:
    name: swag_internal_network
    connected:
      - "{{ container_name }}"
    appends: yes