---
- name: Create a login user
  become: yes
  user:
    name: "{{ username }}"
    password: "{{ password | password_hash('sha512') }}"
    groups: 
      - sudo
    state: present
    update_password: on_create

- name: Allow 'sudo' group to have passwordless sudo
  become: yes
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: Copy the public SSH key 
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ public_ssh_key }}"

- name: Create additional users (no login)
  become: yes
  user:
    name: "{{ item.name }}"
    groups: "{{ item.groups }}"
    password: "{{ item.password | password_hash('sha512') }}"
    state: present
    shell: /sbin/nologin
  with_items: "{{ additional_users }}"
  when: additional_users is defined
