---
    
- name: Make sure the Vaultwarden container is created and running
  docker_container:
    name: 'bitwarden'
    image: "vaultwarden/server"
    pull: true
    state: 'started'
    env:
      WEBSOCKET_ENABLED: "true"
      INVITATIONS_ALLOWED: "false"
      SIGNUPS_ALLOWED: "false"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/data"
    restart_policy: unless-stopped