mysql_db: "nextcloud_db"

mysql_user: "nextcloud"

container_name: nextcloud

dashboard_url: "https://{{ subdomains['nextcloud'] }}.{{ host }}"

health_url: "http://{{ lan_address }}:3000/https://{{ subdomains['nextcloud'] }}.{{ host }}"

homer_category: services