---
- name: Create all the necessary groups
  group:
    name: "{{ item }}"
    state: present
  with_items: 
    - docker
    - sudo

- name: Install aptitude using apt
  apt: 
    name: aptitude 
    state: latest 
    update_cache: yes 
    force_apt_get: yes

# Set up the shell environment and install essential packages
- name: Suppress login messages
  file:
    name: /home/{{ username }}/.hushlogin
    state: touch
    modification_time: preserve
    access_time: preserve

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: "yes"
    update_cache: yes
    cache_valid_time: 86400 

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  reboot:
  when: reboot_required_file.stat.exists == true

- name: Install extra packages
  apt: 
    name: "{{ item }}" 
    state: latest 
    update_cache: yes
  with_items: "{{ extra_packages }}"
  
- name: Clone the latest dotfiles repo
  git:
    repo: "{{ dotfiles_repo }}"
    dest: /home/{{ username }}/dotfiles
    force: yes
    recursive: no

- name: Stow the dotfiles
  shell: cd /home/{{ username }}/dotfiles && stow -v */
  register: stow_result
  changed_when: stow_result.stdout != ""

- name: Set the default shell
  user: 
    name: "{{ username }}"
    shell: "{{ shell }}"

- name: Set the correct ownership for the user's home folder
  file:
    path: /home/{{ username }}
    owner: "{{ username }}"
    group: "{{ username }}"
    recurse: yes

- name: Set the hostname
  hostname:
    name: "{{ inventory_hostname }}"
