---
- name: Add Crowdsec GPG apt Key
  apt_key:
    url: https://packagecloud.io/crowdsec/crowdsec/gpgkey
    state: present

- name: Add Crowdsec Repository
  apt_repository:
    repo: "deb [arch=amd64] https://packagecloud.io/crowdsec/crowdsec/ubuntu focal main"
    state: present
    
- name: Update apt and install Crowdsec and Prometheus
  apt: 
    update_cache: yes 
    name:
      - crowdsec
      - crowdsec-firewall-bouncer-iptables
      - prometheus
    state: present

- name: cscli hub update
  command:
    cmd: cscli hub update
  changed_when: false
    
- name: Install the necessary collections
  command:
    cmd: "sudo cscli collections install crowdsecurity/{{ item }}"
  with_items:
    - nginx
    - sshd
    - linux
    - iptables
  register: collections_install_result
  changed_when: "'overwrite' not in collections_install_result.stderr"

- name: Enable the Prometheus endpoint
  lineinfile:
    path: "/etc/crowdsec/config.yaml"
    line: "  enabled: true"
    search_string: "enabled: false"
    insertafter: "^prometeus:.*$"
  notify:
    - Restart prometheus
    - Restart crowdsec

- name: Increase ban time
  replace:
    path: "/etc/crowdsec/profiles.yaml"
    regexp: 'duration: [0-9]h'
    replace: 'duration: 999h'
  notify:
    - Restart crowdsec

- name: Start and enable Crowdsec services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
      - crowdsec
      - crowdsec-firewall-bouncer
      - prometheus
