---
- name: Make sure the swag_internal container is created and running
  docker_container:
    name: "swag_internal"
    image: "ghcr.io/linuxserver/swag"
    pull: yes
    networks:
      - name: swag_internal_macvlan
        ipv4_address: 10.0.0.24
    capabilities: 
      - net_admin
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
      "URL": "{{ host_local }}"
      "SUBDOMAINS": "wildcard"
      "VALIDATION": "dns"
      "DNSPLUGIN": "cloudflare"
      "EMAIL": "{{ email }}"
    volumes:
      - "{{ docker_dir }}/swag/internal/nginx:/config/nginx"
      - "{{ docker_dir }}/swag/dns-conf:/config/dns-conf"
      - "{{ docker_dir }}/swag/letsencrypt:/config/etc/letsencrypt"
    restart_policy: unless-stopped

- name: Make sure the swag_public container is created and running
  docker_container:
    name: "swag_public" 
    image: "ghcr.io/linuxserver/swag"
    pull: yes
    networks:
      - name: swag_public_macvlan
        ipv4_address: "{{ '.'.join(dmz_gateway.split('.')[0:3]) }}.44"
    capabilities: 
      - net_admin
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
      "URL": "{{ host }}"
      "SUBDOMAINS": "wildcard"
      "VALIDATION": "dns"
      "DNSPLUGIN": "cloudflare"
      "EMAIL": "{{ email }}"
    ports:
      - "443:443"
    volumes:
      - "{{ docker_dir }}/swag/public/nginx:/config/nginx"
      - "{{ docker_dir }}/swag/dns-conf:/config/dns-conf"
      - "{{ docker_dir }}/swag/letsencrypt:/config/etc/letsencrypt"
    restart_policy: unless-stopped
