- name: Create an internal macvlan network
  docker_network:
    name: swag_macvlan
    driver: macvlan
    driver_options:
      parent: enp2s0
    ipam_config:
      - subnet: "{{ lan_network }}"
        gateway: "{{ lan_gateway }}"

- name: Create an internal network
  docker_network:
    name: swag_internal_network
    ipam_config:
      - subnet: "172.20.0.0/16"

- name: Create a public macvlan network
  docker_network:
    name: swag_public_macvlan
    driver: macvlan
    driver_options:
      parent: enp5s0
    ipam_config:
      - subnet: "{{ dmz_network }}"
        gateway: "{{ dmz_gateway }}"
